### ISSUE TITLE
Failed to save a configuration. Conduits:RuntimeMessage: message reply cannot be cloned.

### ISSUE THREAD

**Issue by ls-1N** [ryosuke0920/Search-Dictionary-Faster#6]
I have recently started getting this error from Haidoku. I don't know how or when these messages started. It happens when I select some text, but not always. I don't know yet what kind of selected text causes this.
>Failed to save a configuration. Conduits:RuntimeMessage: message reply cannot be cloned. 

I am using:
Haidoku 1.17.0
Firefox 79.0 (64-bit)
Ubuntu 20.04

Can I give some extra info? Is there an easy way to export my settings for your troubleshooting?

**Comment by ryosuke0920** [comment]
I know this situation few hours ago and I don't yet see why they happen. But for just avoid these error messages coming, you can change settings to not save history when link was clicked or shown wiki pages.

**Comment by ryosuke0920** [comment]
This issue probably come from Firefox 79 changes...
https://bugzilla.mozilla.org/show_bug.cgi?id=1657384

**Comment by ryosuke0920** [comment]
Fixed in Firefox81.
